### PR TITLE
Adding lint config

### PR DESCRIPTION
**Pull request by d-3nnis**
Ran the linter on our files.

### CODE REVIEW

**Review by andrewjrae — APPROVED** [review]
Looks awesome, does it look like it should be easy to add python linting as well?

**Comment by d-3nnis** [comment]
I don't think it should be too difficult, although that will cut into our monthly minutes.

**Comment by andrewjrae** [comment]
Okay, well it would still be nice, and worst case we limit how frequently they happen, or just commit small changes locally.

**Comment by d-3nnis** [comment]
So currently, this lint takes total ~50 seconds, so double that is 100 seconds.I dont think we'll exceed 1200 pushes a month.

**Pull request merged**
